### ISSUE TITLE
Rename to typed-process-effectful

### ISSUE THREAD

**Issue by arybczak** [haskell-effectful/typed-process-effectful#2]
Let's follow the convention set by e.g. `optics`. There's `aeson-optics` etc., not `optics-aeson` etc.

**Comment by arybczak** [comment]
@mmhat do you plan on cleaning things up and making a release? I'm basically asking whether you're willing to maintain this package :slightly_smiling_face:

**Comment by mmhat** [comment]
@arybczak  Yes, I plan to maintain this package and (at least) co-maintaining some of the packages in this organisation. I am however currently busy chopping GHC into pieces (modularising it)...
