### ISSUE TITLE
Consider reusing Effectful.Process.Process effect

### ISSUE THREAD

**Issue by mmhat** [haskell-effectful/typed-process-effectful#3]
Following the discussions after the effects talk at BobKonf 2023 it is not clear to me  why we shouldn't reuse the `Process` effect defined in `Effectful.Process` of the `effectful` package. As both `TypedProcess` and `Process` are static effects with compatible representation and the different semantics are captured in the operations it is possible for them to share the effect in the effect row, i.e. `Process :> es => Eff es a` instead of `(Process :> es, TypedProcess :> es) => Eff es a`. I am not sure if I am missing something here.

@arybczak Do you remember why we went with two separate effects in the first place? I know we had a discussion about that, but I couldn't find anymore.

**Comment by arybczak** [comment]
> @arybczak Do you remember why we went with two separate effects in the first place? I know we had a discussion about that, but I couldn't find anymore.

We did? :D I don't remember. Having just `Process` sounds good to me.

**Comment by mmhat** [comment]
> We did? :D I don't remember.

Forgetful me; You're right, we didn't! The reasons I chose different names is because `Process`/`runProcess` clashes with names from `typed-process`. See https://github.com/haskell-effectful/typed-process-effectful/pull/4 for a solution.
